service: download-payslip

provider:
  name: aws
  runtime: python3.6
  region: ap-northeast-1
  stage: prod

plugins:
  - serverless-python-requirements

package:
  exclude:
    - config.json
    - package.json
    - package-lock.json
    - requirements.txt

custom:
  pythonRequirements:
    dockerizeZip: true
    pythonBin: ${file(./config.json):python_bin}

functions:
  main:
    handler: handler.main
    name: download-payslip
    timeout: 60
    environment:
      SLACK_TOKEN: ${file(./config.json):token}
      SLACK_CHANNEL_ID: ${file(./config.json):channel_id}
      PASSWORD: ${file(./config.json):password}
      WORKER_ID: ${file(./config.json):worker_id}
      TARGET_URL: ${file(./config.json):target_url}
