service: download-payslip

provider:
  name: aws
  runtime: python3.6
  region: ap-northeast-1
  stage: prod
  apiKeys:
    - name: defaultKey
      value: ${file(./config.json):api_key}
  environment:
    SELENIUM_LAYER_SERVICE: selenium-layer

plugins:
  - serverless-python-requirements

package:
  exclude:
    - config.json
    - config.sample.json
    - package.json
    - package-lock.json
    - requirements.txt
    - bin/**
    - selenium-layer/**
    - node_modules/**
    - .python-version
    - README.md

custom:
  pythonRequirements:
    dockerizeZip: true
    pythonBin: ${file(./config.json):python_bin}

functions:
  main:
    handler: handler.main
    name: download-payslip
    timeout: 60
    layers:
      - ${cf:${self:provider.environment.SELENIUM_LAYER_SERVICE}-${opt:stage, self:provider.stage}.SeleniumLayerExport}
      - ${cf:${self:provider.environment.SELENIUM_LAYER_SERVICE}-${opt:stage, self:provider.stage}.ChromedriverLayerExport}
    environment:
      SLACK_TOKEN: ${file(./config.json):token}
      SLACK_CHANNEL_ID: ${file(./config.json):channel_id}
      PASSWORD: ${file(./config.json):password}
      WORKER_ID: ${file(./config.json):worker_id}
      TARGET_URL: ${file(./config.json):target_url}
    events:
      - http:
          path: /
          method: post
          private: true
          cors: true
          response:
            headers:
              Content-Type: "'application/json'"
